[workspace]
resolver = "2"
members = ["flappy_bird", "proc_gen", "sandbox", "top_down"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.15.0"
